
apiVersion: v1
kind: Deloyment 
metadata:
 name:2048
spec:
  replica: 2
  selector:
   matchlabels:
     name: 2048
  template:
    metadata:
      lables:
      name: 2048
    spec:
      containers:
        - name: 2048game
          image: vijaysai1718/2048:latest 
          ports: 
          -containerport: 3000
---
apiversion: v1
kind: Service
metadata:
 name: 2048-service
spec:
 selector: 
  labels:
   name: 2048
  ports:
   - protocol: tcp
     port: 3000
     targetport: 3000
  type: LoadBalancer