apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048
spec:
  replicas: 2
  selector:
    matchLabels:
      name: 2048
  template:
    metadata:
      labels:
        name: 2048
    spec:
      containers:
        - name: 2048game
          image: vijaysai1718/2048:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: 2048-service
spec:
  selector:
    name: 2048
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
